### ISSUE TITLE
Update prop-types to use the npm package instead of deprecated one from React package

### ISSUE THREAD

**Issue by mrancourt** [mcumpl/react-lightweight-tooltip#223]
PropTypes from the main React package has been deprecated and will be removed in React 16.0

```
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  
React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, 
compatibility, migration and more, see https://fb.me/prop-types-docs
```

**Comment by phillipj** [comment]
Opened https://github.com/mcumpl/react-lightweight-tooltip/pull/224 to convert to using the prop-types package.

**Comment by mikeLspohn** [comment]
any word on this being merged?

**Comment by tvilon** [comment]
This MR looks good :) Can you merge it, it will prevent people from updating to React 16

**Comment by mcumpl** [comment]
Just merged it. Thanks.
